name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js  # 如果你的项目需要构建步骤 (例如，使用了 npm)
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 或者你需要的 Node.js 版本

      - name: Install dependencies # 如果你的项目需要构建步骤
        run: npm install # 或者 yarn install, pnpm install

      - name: Build project # 如果你的项目需要构建步骤 (例如, 构建静态站点)
        run: npm run build # 或者 yarn build, pnpm build，根据你的 package.json 配置

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ #  如果构建产出在 dist 目录，则改为 ./dist

