name: Deploy to GitHub Pages

env:
  API_KEY: ${{ secrets.API_KEY }}
  API_ENDPOINT: ${{ secrets.API_BASE_URL }}

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build project
        run: |
          echo "构建时替换环境变量"
          sed -i "s|__API_KEY__|${API_KEY}|g" js/main.js
          sed -i "s|__API_ENDPOINT__|${API_ENDPOINT}|g" js/main.js
          mkdir -p build
          cp -r *.html css js build/
          echo "查看 build 目录内容："
          ls -la build
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build/
          
      - name: Deploy
        uses: actions/deploy-pages@v2